### ISSUE TITLE
What criteria does DocsForge follow for choosing between <> and "" for #includes?

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#21]
Hi,

in [my library's documentation](https://breath.docsforge.com/), `#include` directives for files that belong to the library are all shown in the `<>` form, although I always use `""` in the code.

Doxygen version 1.8.18 (a1b07ad0e92e4526c9ba1711d39f06b58c2a7459) seems to show the expected form, instead. Note that I don't have `FORCE_LOCAL_INCLUDES` enabled. Why does DocsForge differ, in this regard?

**Comment by erez-o** [comment]
You're correct, I currently disregard the distinction between `""` and `<>`.

I added it to my todo list. 

I investigated a bit and it seems that doxygen exports this distinction in the xml, so it shouldn't take long to fix.

**Comment by erez-o** [comment]
Fixed in development server. Will be released in a few days.

Added `FORCE_LOCAL_INCLUDES` option to the docsforge.yaml 

Please check in a week and report if it works, and I'll close this issue.

**Comment by gennaroprota** [comment]
Thanks. However, as I mentioned, it works as expected on my machine, even though that option is set to "NO".

**Comment by erez-o** [comment]
Before this change, I always showed `<>` regardless of the  `FORCE_LOCAL_INCLUDES` flag.

From doxygen's manual:

> If the FORCE_LOCAL_INCLUDES tag is set to YES then doxygen will list include files with double quotes in the documentation rather than with sharp brackets.

Yours was set to NO that's why the `<>` should be shown in doxygen's output as well. 

When I update the server you will be able to display `""` if you desire by changing `FORCE_LOCAL_INCLUDES` to Yes.

**Comment by erez-o** [comment]
Added `FORCE_LOCAL_INCLUDES` in version 3.4.16, see [docs](https://help.docsforge.com/master/autodoc-settings/#force_local_includes).

**Comment by gennaroprota** [comment]
Thank you. What happens if I add the option to my `docsforge.yaml` before version 3.4.16? Do unrecognized options just generate a warning?

**Comment by erez-o** [comment]
Yes, I validate the `docsforge.yaml`

**Comment by gennaroprota** [comment]
Yes, but I was wondering if encountering an unknown option caused a warning or an error. Anyway, I just tried it and can confirm that it works nicely.
