### ISSUE TITLE
Duplicated paragraph titles

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#25]
Hi again,

throughout my documentation ([breath.docsforge.com]()) some paragraph titles are duplicated. It seems that this happens with all paragraphs created with a \par command (but I haven't done an exhaustive verification). Examples are:

 - https://breath.docsforge.com/master/api/breath/to_lowercase/ (paragraph "Naming Rationale")
and
 - https://breath.docsforge.com/master/api/#BREATH_ASSERT (paragraph "Rationale"; please, click "Show More" if needed)

**Comment by erez-o** [comment]
Thanks, I noticed it and already fixed in my dev server. See #24

**Comment by gennaroprota** [comment]
Thanks. I had seen #24, but since it didn't mention what the problem was... :-)
