### ISSUE TITLE
Triple hyphen ("---") disappers from the output

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#29]
Hi,

it seems that a sentence like this:

    At the time of this writing---October 30, 2020---I'm reporting an issue here.

is rendered as:

    At the time of this writingOctober 30, 2020I'm reporting an issue here.

by DocsForge, eating up each instance of "---". The issue doesn't appear to be with Doxygen (I tried with both settings for the `MARKDOWN_SUPPORT` option, just in case). An example in my documentation is [here](https://breath.docsforge.com/master/api/breath/crc/) (you can search for "at the time of this writing").

P.S.: perhaps it would be better to link to a specific revision on GitHub in our issue reports? Because, considering e.g. the link to the DocsForge documentation above, nobody could see the problem if they followed the link two years from now, when the issue will have been fixed.

**Comment by gennaroprota** [comment]
If you agree, I'd just delete this issue. It was never meant to be filed, and I'm not sure how that happened.

**Comment by erez-o** [comment]
Sure :)

**Comment by gennaroprota** [comment]
Good :-) Of course, I can't do that myself, because I'm not the account owner (I'm sure you know).
