### ISSUE TITLE
Title of \pre and \post paragraphs

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#31]
Hi,

it seems that DocsForge correctly renders `\pre` and `\post` documentation with separate paragraphs but gets their titles wrong; see the attached image.

![screenshotForDocsForgeIssue](https://user-images.githubusercontent.com/4961853/98126160-9012d800-1eb5-11eb-83b7-559d12857b1e.png)

**Comment by erez-o** [comment]
Thanks for reporting, I'll check on it.

**Comment by gennaroprota** [comment]
Thank \*you\*!

**Comment by erez-o** [comment]
Fixed and released on version 3.4.17.

`/pre` and `/post` titles are now rendered with titles `Precondition` and `Postcondition`.

Closing issue, please reopen if you find any problems. Cheers :)

**Comment by gennaroprota** [comment]
Thanks. To let my pedantic self get completely out :-), I'd prefer the plural, in this case ("Preconditions" and "Postconditions"), but I'll leave it up to you. Doxygen uses the singular. "Precondition" could also be replaced with "Requires", and "Postcondition" with "Ensures", but that's probably deviating too much from what people are used to by using Doxygen.

**Comment by erez-o** [comment]
:) I agree, but currently it's better if I'm consistent with Doxygen regarding this issue.
