### ISSUE TITLE
Avoiding autolinking words preceded by '%'

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#33]
Hi,

Doxygen allows the user to prevent a word from being autolinked by putting a `%` in front of the word. I think (though I've not verified that), given the regular expressions listed in the documentation and the fact that DocsForge acts (AFAIU) after Doxygen has produced its output, that DocsForge would link such a word anyway. That would be against the user will, of course.

I'm not sure how to fix this, as I guess the % sign is simply absent in the Doxygen output.

Note that all of the above is speculative and might just be my imagination of how things would go. But I didn't want to lose the opportunity to report the issue, in case it's really an issue.

**Comment by erez-o** [comment]
I don't see in [doxygen's documentation regarding autolink](https://www.doxygen.nl/manual/config.html#cfg_autolink_support) a `%` . 

Currently, this doxygen flag is always enabled when running docsforge.

On top of that, Docsforge has a more greedy auto-linking implementation that can be disabled all together with [`autolink:false`](https://help.docsforge.com/master/additional-settings/#autolink), or it can be limited by excluding a list of words using [`autolink_exclude`](https://help.docsforge.com/master/additional-settings/#autolink_exclude)

I strongly suggest enabling `autolink:true` and using `autolink_exclude` to tweak it, and if it's needed, I'll add `autolink_exclude_pattern` and `autolink_include_pattern` that will let users exclude/include any regex pattern.

`autolink:false` would also disable any links in markdown pages, mentioned in, or source browsing, so I really don't recommend it.

I do maintain a list of common [english words](https://github.com/erez-o/docsforge/blob/master/utils/common_words.txt) excluded by default for all packages. For example, if you have a function named `do`, not every `do` found will be autolinked, but only if followed by something that resembles a C/C++ method - `do(...)` or `do<...>`

**Comment by gennaroprota** [comment]
The relevant documentation is [here](https://www.doxygen.nl/manual/autolink.html). It says:

<blockquote>
If you want to prevent that a word that corresponds to a documented class is replaced by a link you should put a % in front of the word.
</blockquote>

Yes, I currently have `autolink: true` and `autolink_exclude` (with just one word in it, for now).

About `do`, that's a keyword in C++ (and in several other languages I know of), so I can't have a function with that name :-)

**Comment by erez-o** [comment]
Yeah, forgot that `do` is a bad example :) the list of excluded common words has around 60,000 words so any other example word would do.

Thanks for finding the relevant documentation, I didn't know about it. 
I don't plan on supporting it when `autolink:true`.

Maybe it's a personal preference, but I don't think it's a good approach to add `%` in your code as a way of solving it because 99% of programmers reading the code (and not the html) won't understand what it means.
