### ISSUE TITLE
Odd rendering of \throw paragraphs

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#34]
Hi,

the following markup:

```
//!     \throw
//!         A \c std::invalid_argument if any of the characters in \c s
//!         is not a decimal digit (i.e. one of \c 0123456789).
```

is being rendered as follows in my documentation:

![DocsForgeOutputScreenshot](https://user-images.githubusercontent.com/4961853/98230446-6e6c2c00-1f5b-11eb-9884-7bc56b8a21b0.png)

That has two oddities:

 1. The initial "A" appears as code

 2. An extra hyphen appears between the "A" and the rest

I suspect the glitches are due to Doxygen, though, because this is Doxygen's output, instead:

![DoxygenOutputScreenshot](https://user-images.githubusercontent.com/4961853/98230866-f3574580-1f5b-11eb-8ebe-f7d25de8549d.png)

There, although there's no extra hyphen, the "A" is rendered as a parameter name (!).

**Comment by erez-o** [comment]
Yes, it's doxygen.

Doxygen's xml output in this case is:

```xml
<parameterlist kind="exception">
  <parameteritem>
    <parameternamelist>
      <parametername>A</parametername>
    </parameternamelist>
    <parameterdescription>
    <para>
    <computeroutput>std::invalid_argument</computeroutput>
    if any of the characters in
    <computeroutput>s</computeroutput>
    is not a decimal digit (i.e. one of
    <computeroutput>0123456789</computeroutput>
    ).
    </para>
    </parameterdescription>
  </parameteritem>
</parameterlist>
```

It thinks A is `<parametername>A</parametername>`. The hyphen in docsforge is added automatically after a parameter name.

Just a suggestion - can't a `\par exception` achieve your desired behavior?

**Comment by gennaroprota** [comment]
Yes, indeed, `\par Exceptions` seems the best solution. Thanks for the suggestion, and for looking into this.

**Comment by gennaroprota** [comment]
Addendum: that's actually the expected behavior (if you know what to expect :-)). Because the `\throw` command has a mandatory argument, which is supposed to be the type of exceptions emitted. If e.g. you follow "\throw" with "A \c std::invalid_argument", then "A" is taken as the type of exceptions, and formatted as code. In a sense, this is "logical", because `\throw` wouldn't be any different from `\par`, otherwise. In fact, I'd say that, given this hard-coded logic, it's probably better to just use `\par`, which is more flexible.

Sorry for the bogus issue report.

**Comment by gennaroprota** [comment]
Addendum to the addendum :-): is the colon after "Exceptions" (the paragraph title) intentional? It seems odd at the end of a title.

**Comment by erez-o** [comment]
I agree, adding a colon is inconsistent with other paragraphs, and since it's a `<dt>` element anyway, there's no need for it.

I'll fix it, thanks.

Closing, if you notice in the future that it still exists, please reopen.

**Comment by erez-o** [comment]
Fixed inconsistent colons for various titles like "Exceptions" on version 3.4.17.
