### ISSUE TITLE
Variables added from the README documentation

### ISSUE THREAD

**Issue by biojppm** [erez-o/docsforge#39]
In https://rapidyaml.docsforge.com/master/api/#variables we can see some variables. They do not come from the source code, but from some samples in the main README.

How can I avoid these?

**Comment by erez-o** [comment]
1) The variables come from the source code - lines 21 & 22 of preprocessor.cpp, see [here](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/preprocess.cpp#L21)

    It looks like a bug in doxygen reading the code (docsforge uses doxygen's xml output).

    Attaching a zip of doxygen's html output: 

    [rapidyaml_master.zip](https://github.com/erez-o/docsforge/files/5564790/rapidyaml_master.zip)

    look at the output of `rapidyaml_master/preprocess_8cpp.html`

2) It looks like a bug in doxygen's handling of anonymous namespaces - When I changed [this namespace](https://github.com/biojppm/rapidyaml/blob/master/src/c4/yml/preprocess.cpp#L18) from anonymous to a named one the variables are read correctly as part of `struct _SubstrWriter`

3) If you can report the issue to doxygen that would be great. Note that it takes time for them to release a new version.

4) In docsforge there's an easy way to hide them, simply exclude these variables by name.

    Add to your configuration file:

    ```
    excludeApi:
    - buf
    - pos
    ```

**Comment by biojppm** [comment]
OK, thanks again for investigating and clarifying. Now I understand better how Docsforge works.
