### ISSUE TITLE
Broken link in Home / Versions

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#45]
Hi Erez,

just noticed that the link "edit your profile settings", in Home / Versions, is broken. I'm not sure what the correct URL is, but it currently points to https://project_name.docsforge.com/profile/edit, while the corresponding link from the profile page (which works for me) goes to https://docsforge.com/profile/edit/.

Cheers.

**Comment by erez-o** [comment]
Thanks, nice catch :)

**Comment by gennaroprota** [comment]
You're welcome! :-)

**Comment by erez-o** [comment]
Fixed, thx again.
